XCentiumWebScraper/Controllers/UrlScraperController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using XCentiumWebScraper.Core;
using XCentiumWebScraper.Core.Model;

namespace XCentiumWebScraper.Controllers
{
    public class UrlScraperController : Controller
    {
        /// <summary>
        /// Homepage
        /// Displays url input field and history of previous executions
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        public ActionResult Dashboard()
        {
            var historyItems = Scraper.ReadHistory();
            return View(historyItems);
        }

        /// <summary>
        /// Scrapes html page for image and text data
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        public ActionResult Scrape(string url)
        {
            Scraper scraper = new Scraper(url);
            if(scraper.Loaded) scraper.Execute();

            return scraper.DocInfo != null 
                ? View("~/Views/UrlScraper/Results.cshtml", scraper.DocInfo) 
                : null;
        }

        /// <summary>
        /// Displays prerecorded data on a previously run url
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult History(Guid id)
        {
            DocInfo item = Scraper.ReadHistoryItem(id);
            return item != null 
                ? View("~/Views/UrlScraper/Results.cshtml", item)
                : null;
        }

        public ActionResult ClearHistory()
        {
            Scraper.ClearHistory();
            return RedirectToAction("Dashboard");
        }
    }
}

XCentiumWebScraper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Url Scraping Tool</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Url Scraper", "Dashboard", "UrlScraper", new { }, new { @class = "navbar-brand home-link" })
            </div>
        </div>
    </div>

    <div class="container body-content">
        <section>
            <form action="@Url.Action("Scrape", "UrlScraper")">
                <div class="row">
                    <div class="col-lg-10 col-md-10 col-sm-12">
                        <input id="url" name="url" type="url" class="form-control" placeholder="Insert URL here">
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-12">
                        <input type="submit" name="submit" value="Go!" class="btn btn-success" />
                    </div>
                </div>
            </form>
        </section>
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year - XCentium Test Application</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script src="~/Scripts/Site.js"></script>
</body>
</html>

XCentiumWebScraper/Views/UrlScraper/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
@using XCentiumWebScraper.Core
@model IEnumerable<XCentiumWebScraper.Core.Model.DocInfo>

<section>
    @if (Model != null && Model.Any())
    {
        @Html.ActionLink("Clear history", "ClearHistory", "UrlScraper", new { }, new { @class = "" })
        <ul>
            @foreach (var item in Model)
            {
                <li>@item.RunDate.ToString(Constants.DateFormatString) @Html.ActionLink(item.Url, "History", "UrlScraper", new { id = item.Id }, new { @class = "" })</li>
            }
        </ul>
    }
    else
    {
        <h4>There are no items in history to view</h4>
    }
</section>

XCentiumWebScraper/Views/UrlScraper/Results.cshtml
@{
    ViewBag.Title = "Results";
    var activeStatus = "active";
}
@using XCentiumWebScraper.Core
@model XCentiumWebScraper.Core.Model.DocInfo

<section id="imageresults">
    <h1>Results for @Model.Url</h1>
    <h3>Image Results</h3>
    @if (Model.Images != null && Model.Images.Any())
    {
        <div id="carouselComponent" class="carousel slide" data-ride="carousel" aria-label="Carousel Image Slider">
            <div class="carousel-inner">
                @foreach (var slide in Model.Images)
                {
                    <div class="carousel-item @activeStatus">
                        <img src="@slide" alt="@slide">
                    </div>

                    if (activeStatus == "active")
                    {
                        activeStatus = "";
                    }
                }
            </div>
            <a class="carousel-control-prev left" href="#carouselComponent" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon icon-arrow-circle-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next right" href="#carouselComponent" role="button" data-slide="next">
                <span class="carousel-control-next-icon icon-arrow-circle-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    }
    else
    {
        <h4>There are no image items to display</h4>
    }
</section>
<section id="wordresults">
    <h3>Word Data Results</h3>
    <div>
        <div><strong>Total Word Count: </strong> @Model.TotalWordCount</div>
        <div><strong>Total Unique Words: </strong> @Model.UniqueWordCount</div>
        <div><strong>Most Used Words: </strong> @string.Join(", ", Model.TopWords.Select(w => w.Word))</div>
        <canvas id="wordChart" width="400" height="200"></canvas>

        @for (int i=1; i<=Model.TopWords.Count; i++)
        {
            <input type="hidden" id="wc_word_@i" value="@Model.TopWords[@i-1].Word" />
            <input type="hidden" id="wc_count_@i" value="@Model.TopWords[@i-1].Count" />
        }
    </div>
</section>